### ISSUE TITLE
トップページでテキストを選択したときの色

### ISSUE THREAD

**Issue by igrep** [haskell-jp/haskell-jp.github.io#21]
https://github.com/haskell-jp/blog/issues/177 の修正を確認しているときに気づいたんですが、 https://haskell.jp のトップには

```css
a:focus {
  color: #d66c79;
}
```
や

```css
::selection {
  color: white;
  text-shadow: none;
  background: #d66c79;
}
```

があたってない！
